name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.4
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Lint (black)
      run: poetry run black . --check
    - name: Lint (flake8)
      run: poetry run flake8 . --count --show-source --statistics
    - name: Test (pytest)
      run: DYNACONF_GITLAB__TOKEN=dummy-token poetry run pytest tests
